Vagrant.configure("2") do |config|
  config.vm.define "server" do |server|
    server.vm.box = "generic/rocky9"
    server.vm.hostname = "server"

    server.vm.network "private_network", ip: "192.168.40.254"

    server.vm.provider "vmware_desktop" do |v|
      v.vmx["displayName"] = "rocky9-server"
      v.vmx["memsize"] = "2048"
      v.vmx["numvcpus"] = "2"
    end

    server.vm.provision "shell", path: "bootstrap.sh", run: "once"
  end
end
